import Header from "@/components/Header/Header";
import InventoryTable from "@/components/InventoryTable/InventoryTable";
import TablePlaceholder from "@/components/TablePlaceholder/TablePlaceholder";
import useInventoryStore from "@/zustand/inventory";
import Head from "next/head";

export default function Home() {
  const inventory = useInventoryStore((state) => state.inventory);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-screen-lg py-[28px] sm:py-[38px]">
        <Header />
        <main className="mt-[40px]">
          {!!inventory.length ? <InventoryTable /> : <TablePlaceholder />}
        </main>
      </div>
    </>
  );
}
